
services:
  drupal:
    image: drupal:10
    container_name: drupal
    ports:
      - "8080:80"
    environment:
      DRUPAL_DB_HOST: db
      DRUPAL_DB_USER: drupaluser
      DRUPAL_DB_PASSWORD: drupalpassword
      DRUPAL_DB_NAME: drupal
    volumes:
      - drupal_data:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8
    container_name: drupal_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupaluser
      MYSQL_PASSWORD: drupalpassword
    command:
      --default-authentication-plugin=mysql_native_password
    volumes:
      - db_data:/var/lib/mysql

volumes:
  drupal_data:
  db_data:
